[package]
name = "rsfilc"
version = "0.3.0"
edition = "2021"
authors = ["Jeromos Kovács <iitsnotme214@proton.me>"]
description = "A Kréta API and client(cli and TUI: todo!) written entirely in Rust from the ground up."
keywords = ["kreta", "api", "client", "hungarian"]
categories = ["command-line-interface"]
repository = "https://codeberg.org/jark/kreta-rs"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.22.0"
chrono = "0.4.37"
clap = { version = "4.5.4", features = ["derive"] }
dirs = "5.0.1"
hmac = "0.12.1"
reqwest = "0.12.1"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
sha2 = "0.10.8"
tokio = { version = "1.36.0", features = ["full"] }
