[package]
name = "rsfilc"
version = "0.8.4"
edition = "2021"
authors = ["Jeromos Kovács <iitsnotme214@proton.me>"]
description = "A Kréta API and console client: cli and todo!(\"TUI\"), written entirely in Rust from the ground up."
keywords = ["kreta", "api", "client", "hungarian"]
categories = ["command-line-interface"]
repository = "https://codeberg.org/jark/rsfilc"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.22.0"
chrono = "0.4.37"
clap = { version = "4.5.4", features = ["derive"] }
clap_complete = "4.5.2"
dirs = "5.0.1"
fern = "0.6.2"
hmac = "0.12.1"
log = "0.4.21"
reqwest = { version = "0.12.1", default-features = false, features = [
  "blocking",
  "rustls-tls-native-roots",
] }
rpassword = "7.3.1"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
sha2 = "0.10.8"
toml = "0.8.12"
