name: Rust

on:
  push:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  CARGO_PROFILE_TEST_DEBUG: 0

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
          os: [macos-latest, ubuntu-latest, ubuntu-24.04-arm, windows-latest]

    steps:
      - uses: actions/checkout@v4
      - uses: swatinem/rust-cache@v2

      - name: Run tests
        run: cargo test --verbose --locked

      - name: Run cargo fmt
        run: cargo fmt --all --check

      - name: Run cargo clippy
        run: cargo clippy --all-targets --locked

      - name: Build in release mode
        run: cargo build --release --verbose --locked

      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: tuna-man_${{ runner.os }}_${{ runner.arch }}
          path: |
              target/release/rsfilc
              target/release/rsfilc.exe
